remote_theme: chesterhow/tale

title: magnostherobot
email: magtherob@gmail.com
description: >
    My website, where I might write things, maybe.
url: "https://magnostherobot.github.io"
github_username: magnostherobot

markdown: kramdown
permalink: /:year/:title:output_ext

paginate: 5

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
